# noexcept

noexcept 说明符 (C++11 起)，指定函数是否抛出异常。

noexcept	(1)	
noexcept(表达式)	(2)	
throw()	(3)	(C++17 中弃用)(C++20 中移除)

1) 与 noexcept(true) 相同
2) 如果 表达式 求值为 true，那么声明函数不会抛出任何异常。

noexcept 做运算符时，运算符进行编译时检查，在表达式声明不会抛出任何异常的情况下返回 true。

它可用于函数模板的 noexcept 说明符中，以声明函数将对某些类型抛出异常，但不对其他类型抛出。

noexcept 说明不是函数类型的一部分（正如同动态异常说明），而且只能在声明函数、变量、函数类型的非静态数据成员、函数指针、函数引用或成员函数指针时，以及在以上这些声明中声明类型为函数指针或函数引用的形参或返回类型时，作为 lambda 声明符或顶层函数声明符的一部分出现。它不能在 typedef 或类型别名声明中出现。
```cpp
void f2();
void f() noexcept(noexcept(f2())){  // 1. noexcept运算符，noexcept(f2()) 返回 false 2. noexcept(false)
    std::cout << "hello\n";
}

void f2() {  //说明符
    std::cout << "hello\n";
}

int main(){
    std::cout << std::boolalpha << noexcept(f()) << '\n';
    std::cout << std::boolalpha << noexcept(f2()) << '\n';
    auto p = f;
    p();
}
